[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sudoku-strategy"
dynamic = ["version"]
requires-python = ">=3.14"
description = "Library for solving sudoku in Python"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    { name = "blm34", email = "pypi.escalate394@passmail.net"},
]
keywords = ["sudoku"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[project.urls]
Homepage = "https://github.com/blm34/sudoku-strategy/"
Repository = "https://github.com/blm34/sudoku-strategy/"
Issues = "https://github.com/blm34/sudoku-strategy/issues"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "ty>=0.0.78",
]
tests = [
    "hypothesis>=6.168.2",
    "pytest>=9.1.1",
]
